sudo: False
language: python
dist: trusty
python:
    - '3.5'

env:
  matrix:
    - TESTENV=lint
    - TESTENV=py27
#    - TESTENV=py35

script:
  - tox -e $TESTENV --recreate 

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#autocrypt"
#    on_success: change
#    on_failure: change
#    skip_join: true
#  email:
#    - pytest-commit@python.org
